---
abstract: 'ƒdd ¸ml‰¸ts tˆ ÎvÎrˇthÔng!'
author:
  - 'Phil Pollard <bennie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Umlautify
no_index:
  directory:
    - t
    - inc
    - t
provides:
  Acme::Umlautify:
    file: lib/Acme/Umlautify.pm
    version: 1.06
requires:
  Test: 0
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=Acme-Umlautify
  repository: git://github.com/bennie/perl-Acme-Umlautify.git
version: 1.06
